export const FETCH_REVERSE_SEARCH_DATA = 'FETCH_REVERSE_SEARCH_DATA';
export const SET_ASIN_ARRAY = 'SET_ASIN_ARRAY';
export const SET_LIST_PAGE_LOADER = 'SET_LIST_PAGE_LOADER';
export const SET_CURRENT_URL = 'SET_CURRENT_URL';
