export const DETAIL_PAGE_LOADER_CHANGE = 'DETAIL_PAGE_LOADER_CHANGE';
export const SET_DETAIL_PAGE_DATA = 'SET_DETAIL_PAGE_DATA';
export const SET_DETAIL_PAGE_PROFIT_CALCULATOR_DATA = 'SET_DETAIL_PAGE_PROFIT_CALCULATOR_DATA';
export const UPDATE_REFERRAL_FEE = 'UPDATE_REFERRAL_FEE';
export const RESET_DETAIL_PAGE_DATA = 'RESET_DETAIL_PAGE_DATA';
